# Generated by Django 2.1.5 on 2019-02-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
